### ISSUE TITLE
Adicionar árvore de decisão no dicionário

### ISSUE THREAD

**Issue by leportella** [PizzaDeDados/datascience-pizza#240]

**Comment by rafaelsakurai** [comment]
Oi. No [dicionário](https://github.com/leportella/datascience-pizza/blob/master/dicionario.md) já tem uma descrição da Árvore de Decisão, a ideia é manter o que tem lá ou detalhar a descrição?

**Comment by rafaelsakurai** [comment]
Acho que essa issue está duplicando o [#233](https://github.com/leportella/datascience-pizza/issues/233).
