### ISSUE TITLE
Adicionar classificação (de aprendizado de maquina) no dicionário

### ISSUE THREAD

**Issue by leportella** [PizzaDeDados/datascience-pizza#241]

**Comment by hugoabonizio** [comment]
Aparentemente [já existe](https://github.com/PizzaDeDados/datascience-pizza/blob/master/dicionario.md#classifica%C3%A7%C3%A3o-aprendizado-de-m%C3%A1quina), ou a definição precisa ser melhorada?

**Comment by jtemporal** [comment]
fixed by #293
