### ISSUE TITLE
Adicionar modelo generativo no dicionário

### ISSUE THREAD

**Issue by leportella** [PizzaDeDados/datascience-pizza#243]

**Comment by murilommen** [comment]
Eu fiz uma PR [aqui](https://github.com/PizzaDeDados/datascience-pizza/pull/389), mas acho que referenciei errado =(

**Comment by jtemporal** [comment]
prontinho @murilommen depois chega lá no Pr que fiz o ajuste antes de dar o merge pra gente fechar automaticamente a issue =)
