### ISSUE TITLE
Adicionar PCA no dicionário

### ISSUE THREAD

**Issue by leportella** [PizzaDeDados/datascience-pizza#254]

**Comment by ullayne02** [comment]
Você gostaria da implementação? se sim, tem como me alocar para essa issue? (:

**Comment by enieber** [comment]
@ullayne02 pelo que eu entendi, basta você colocar a definição do que é PCA no (arquivo dicionario)[https://github.com/leportella/datascience-pizza/blob/master/dicionario.md] e enviar um pull request

**Comment by ullayne02** [comment]
Ah, então posso resolver?

**Comment by enieber** [comment]
sim..

**Comment by leportella** [comment]
@ullayne02 pode resolver sim :) é só colocar uma definição em português com referências :)

**Comment by jtemporal** [comment]
fixed by #307
