### ISSUE TITLE
Padronizar referências no dicionário

### ISSUE THREAD

**Issue by leportella** [PizzaDeDados/datascience-pizza#282]
Temos referências do tipo `Referência`, `ref` ou `1`

Seria legal que todas fossem números

**Comment by fcrespo82** [comment]
Olá @leportella encontrei seu repositório pelo post da [Jessica temporal](https://medium.com/@jessicatemporal/projetos-brasileiros-para-contribuir-nesse-hacktoberfest-versão-2018-4925959b9411) sobre o #Hacktoberfest. Posso ajudar com esta issue?

**Comment by jtemporal** [comment]
fixed by #300
