### ISSUE TITLE
Link da descrição não funciona

### ISSUE THREAD

**Issue by paulochf** [PizzaDeDados/datascience-pizza#310]
[guia.pizzadedados.com](guia.pizzadedados.com) funciona

https://guia.pizzadedados.com não funciona

**Comment by ficosta** [comment]
@paulochf não consegui encontrar em nenhum lugar https://guia.pizzadedados.com e o link está funcionando tb. ;-) Acho q foi solucionado. @leportella

**Comment by paulochf** [comment]
Acabei de testar os links e ainda está com o problema.
