### ISSUE TITLE
Ordenação do Dicionario

### ISSUE THREAD

**Issue by raphamendonca** [PizzaDeDados/datascience-pizza#339]
O Dicionário foi atualizado porém não está apresentando uma ordenação dentro de cada topico/letra.

ex:
- E
-- Ensemble Learning
-- Entropia Cruzada
-- Erro quadrático médio
-- Embeddings

Para uma busca otimizada de quem for consumir esse dicionário seria muito útil que estivesse ordenado os termos. Percebi isso em vários pontos do dicionário.

**Comment by rogerresmini** [comment]
Pus os termos em ordem alfabética e padronizei as referências. Espero ter ajudado.

**Comment by jtemporal** [comment]
Oi @rogerresmini infelizmente não aceitamos o  #375 pois tinha muitas alterações tornando impossível o review, se quiser submeter as alterações individualmente vou adorar revisá-las. 😄
