### ISSUE TITLE
Onde colocar sites de referências?

### ISSUE THREAD

**Issue by paulochf** [PizzaDeDados/datascience-pizza#346]
Onde coloco isso? https://machinelearningmastery.com/start-here/

**Comment by jtemporal** [comment]
Oi @paulochf acho que o local mais indicado é [esse aqui](https://github.com/PizzaDeDados/datascience-pizza/blob/master/topicos/aprendizado-de-maquina.md#tutoriais) Ou no caso, neste mesmo documento numa seção nova chamada `Outros` como [nesse caso aqui](https://github.com/PizzaDeDados/datascience-pizza/blob/master/topicos/deep-learning.md#outros)

**Comment by paulochf** [comment]
Acho que a 1ª opção da @jtemporal é a melhor. 😉

**Comment by jtemporal** [comment]
Aceitaríamos PR com essa adição 👍

**Comment by jtemporal** [comment]
abri a issue #392 para adicionar esse link na sessão indicada =)
