### ISSUE TITLE
Traduzir o termo Clustering no dicionário

### ISSUE THREAD

**Issue by jtemporal** [PizzaDeDados/datascience-pizza#402]
Usar o termo Clusterização no lugar de Clustering, e adicionar uma entrada para Clustering seguindo o que foi feito pela @juliatessler no #396

**Comment by juliatessler** [comment]
Clusterização ou agrupamento? Se bem que, estamos usando clusterização em PT-BR mesmo...

**Comment by jtemporal** [comment]
Sou a favor de Clusterização mesmo
